from django.contrib import admin
from Application.models import *

# Register your models here.
admin.site.register(Patient)
admin.site.register(ActiveUsers)
admin.site.register(SpecificUserLoginDiary)
admin.site.register(ImageType)
admin.site.register(Image)
admin.site.register(ImageReport)
admin.site.register(ReportTooth)
admin.site.register(ReportToothPredict)
admin.site.register(LabelForAddDiagnosis)
# admin.site.register(ApprovedPortalTermsOfUse)
# admin.site.register(AnalysisDetailLog)
admin.site.register(UserInformations)
admin.site.register(ToothTypeIcon)
admin.site.register(TreatmentPlanning)
admin.site.register(IllnessLabel)
admin.site.register(TreatmentMethod)
admin.site.register(IllnessTreatmentMethod)
admin.site.register(TreatmentRecommendationForTooth)
admin.site.register(SuggestImplantToMissingTooth)
admin.site.register(CreateReportForPatient)
admin.site.register(CreateReportForPatientOptions)
admin.site.register(ReportPageIllnessDescriptions)
admin.site.register(ReportMails)
admin.site.register(DoctorChoicesForReport)
admin.site.register(FormQuestion)
admin.site.register(FormWithCompany)
admin.site.register(FormAnswers)
admin.site.register(FormRadiographs)
admin.site.register(SpecificParameter)
admin.site.register(DrawedImplantOrCrown)
admin.site.register(ErrorLog)
admin.site.register(Currency)
admin.site.register(Feedback)

