from django.urls import path, include
from django.contrib import admin
from Application.views import *

urlpatterns = [
    path('login/', login_page, name='loginPage'),
    path('', lambda request: redirect('loginPage')),
    path('validator/', login_page_validator, name='login_page_validator'),
    path('patients', patients_page, name='patientsPage'),
    path('homepage', homepage, name='homepage'),
    path('favorite-patients', favourited_patients_page, name='favourited_patients_page'),
    path('add-patient/', add_patient_page, name='addpatientPage'),
    path('add-patient-form/', add_patient_form, name='add_patient_form'),
    path('add-patient-form-prepare/', add_patient_page_from_form_prepare, name='add_patient_page_from_form_prepare'), #bu api
    path('update-patient/<patient_slug>', add_patient_page, name="addpatientPageSlug"),
    path('diagnosis/<image_report_id>', diagnosis_page, name='diagnosisPage'),
    path('profile', profile_page, name='profilePage'),
    path('logout', log_out, name='logOut'),
    path('forgot-password', forgot_password_page, name='forgot_password_page'),
    path('change-password/<ufpk_id>/', change_password, name='change_password'),
    path('profile', profile_page, name='profile_page'),
    path('update-profile', update_profile_page, name='update_profile_page'),
    path('report/<slug>', old_report_page, name='old_report_page'),
    path('report/<slug>/', report_page, name='report_page'),
    # path('add-user', add_demo_user_page, name='add_user_page'),
    path('add-user', AddPanel.addDoctorOwnCompany, name='addDoctorOwnCompany'),
    path('add-user-distributor', AddPanel.addDistributor, name='addDistributor'),
    path('add-user-to-company', AddPanel.addDoctorDifferentCompany, name='addDoctorDifferentCompany'),
    path('add-user-and-company', AddPanel.addCompanyDoctor, name='addCompanyDoctor'),
    path('add-demo-user', AddPanel.addDemoUser, name='addDemoUser'),
    path('distributor-adds-user', AddPanel.DistributorAddsUser, name='DistributorAddsUser'),
    path('distributor-adds-user-to-company', AddPanel.DistributorAddsUserToCompany, name='DistributorAddsUserToCompany'),
    path('list-user', list_users, name='list_users'),
    path('form/<patient_slug>', send_form_to_patient_page , name='send_form_to_patient_page'),
    path('buy/<course_hash>', buy, name='buy'),
    path('success_buy', success_buy, name='success_buy'),
    path('view-user/<int:id>', view_user, name="view_user"),
    
    path('patient-form', company_form_page, name="company_form_page"),
    path('web-form/<slug>', clinic_form_page_to_patients, name="clinic_form_page_to_patients"),
    path('list-forms', list_forms, name="list_forms"),
    path('cephalometric/<image_report_id>', cephalometric_page, name="cephalometric_page"),
    path('patient-form-detail/<slug>', patient_form_detail, name="patient_form_detail"),
    path('get-ai-treatment-planning-content', treatment_planning_from_AI_request, name='get_content_of_ai_treatment_planning'),
    path('list-activities/<int:id>', list_activities, name="listActivities"),
    path('demo-accounts', demo_accounts_list_page, name="demo_accounts_list_page"),
    path('anaylsis-list', analysis_list_page, name="analysis_list_page"),
    path('purchase-list', purchase_list_page, name="purchase_list_page"),
    path('user-activities-list', user_activities_list_page, name="user_activities_list_page"),
    path('treatment-pricings', treatment_pricing_for_company_page, name="treatment_pricing_for_company_page"),
    # path('ftptest', testftp, name="testftp"),
    path('signup/', signup_page, name='signupPage'),
    
]
