# Generated by Django 4.2.3 on 2024-03-18 09:11

import Wizard.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Application', '0023_currency_and_more'),
        ('User', '0010_purchaserecord_packagepricing_extrapackagepricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_group_name', models.CharField(blank=True, max_length=99, null=True)),
                ('template_group_queue', models.IntegerField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=99, null=True)),
                ('template_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('containing_radiography', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LabelNameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeethImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teeth_number', models.IntegerField(blank=True, null=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=Wizard.models.get_file_path)),
                ('svg_paths_dict', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentNameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_tags', models.TextField(blank=True, null=True)),
                ('diagnosis_data', models.TextField(blank=True, null=True)),
                ('raw_treatment_data', models.TextField(blank=True, null=True)),
                ('image_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.imagereport')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_treatment_data', models.TextField(blank=True, null=True)),
                ('plan_queue', models.IntegerField(blank=True, default=1, null=True)),
                ('plan_pricing', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('general_note', models.TextField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('pdf_file', models.CharField(blank=True, max_length=999, null=True)),
                ('pdf_created_date', models.DateTimeField(blank=True, null=True)),
                ('drawed_radiography_path', models.CharField(blank=True, max_length=500, null=True)),
                ('treatment_wizard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wizard.treatmentwizard')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentNamesForWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=999, null=True)),
                ('tr_name', models.CharField(blank=True, max_length=999, null=True)),
                ('pt_name', models.CharField(blank=True, max_length=999, null=True)),
                ('ar_name', models.CharField(blank=True, max_length=999, null=True)),
                ('fr_name', models.CharField(blank=True, max_length=999, null=True)),
                ('uz_name', models.CharField(blank=True, max_length=999, null=True)),
                ('ru_name', models.CharField(blank=True, max_length=999, null=True)),
                ('nl_name', models.CharField(blank=True, max_length=999, null=True)),
                ('slug', models.CharField(blank=True, max_length=999, null=True)),
                ('sub_label_status', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wizard.treatmentnamegroup')),
                ('sub_of_this', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Wizard.treatmentnamesforwizard')),
            ],
        ),
        migrations.CreateModel(
            name='LabelNamesForWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=999, null=True)),
                ('tr_name', models.CharField(blank=True, max_length=999, null=True)),
                ('pt_name', models.CharField(blank=True, max_length=999, null=True)),
                ('ar_name', models.CharField(blank=True, max_length=999, null=True)),
                ('fr_name', models.CharField(blank=True, max_length=999, null=True)),
                ('slug', models.CharField(blank=True, max_length=999, null=True)),
                ('sub_label_status', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wizard.labelnamegroup')),
                ('sub_of_this', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Wizard.labelnamesforwizard')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraTreatmentPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_treatments', models.CharField(blank=True, max_length=999, null=True)),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wizard.treatmentplan')),
                ('treatment_wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wizard.treatmentwizard')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTreatmentPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=99, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.company')),
                ('treatment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wizard.treatmentnamesforwizard')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicSavedTemplatesForTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates', models.ManyToManyField(blank=True, to='Wizard.documenttemplates')),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wizard.treatmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicModifiedTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.company')),
                ('template', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Wizard.documenttemplates')),
            ],
        ),
    ]
