# Generated by Django 4.2.3 on 2024-03-19 07:56

import Wizard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCoverImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_cover', models.ImageField(blank=True, null=True, upload_to=Wizard.models.get_file_path_for_pdf_cover)),
                ('pdf_finish_cover', models.ImageField(blank=True, null=True, upload_to=Wizard.models.get_file_path_for_pdf_cover)),
            ],
        ),
        migrations.AddField(
            model_name='documenttemplates',
            name='containing_cover_image',
            field=models.BooleanField(default=False),
        ),
    ]
