# Generated by Django 4.2.3 on 2024-03-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wizard', '0002_defaultcoverimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplates',
            name='containing_end_cover_image',
            field=models.BooleanField(default=False),
        ),
    ]
