# Generated by Django 4.2.3 on 2024-03-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wizard', '0003_documenttemplates_containing_end_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentwizard',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
