# Generated by Django 4.2.3 on 2024-03-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wizard', '0004_treatmentwizard_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentwizard',
            name='created_date',
        ),
    ]
