# Generated by Django 3.2.16 on 2024-03-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wizard', '0005_remove_treatmentwizard_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentnamesforwizard',
            name='ai_slug',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
