# Generated by Django 3.2.16 on 2023-07-13 11:16

import Application.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateReportForPatientOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DicomAnalysisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DicomUploadProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_name', models.CharField(blank=True, max_length=100, null=True)),
                ('progress', models.CharField(blank=True, max_length=100, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('question_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('answers', models.CharField(blank=True, max_length=1000, null=True)),
                ('answers_tr', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('queue', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormRadiographs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_answer_group_slug', models.CharField(max_length=100)),
                ('path', models.ImageField(upload_to=Application.models.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='IllnessLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('model_label_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to=Application.models.get_file_path)),
                ('patient_type_id', models.IntegerField(default=0)),
                ('thumbnail_image_path', models.ImageField(blank=True, max_length=160, null=True, upload_to=Application.models.get_file_path, verbose_name='Thumbnail Image Path')),
                ('name', models.CharField(blank=True, max_length=240, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=240)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('result_json', models.TextField(blank=True, null=True)),
                ('is_have_lesion', models.BooleanField(default=False)),
                ('implant_path', models.TextField(blank=True, null=True)),
                ('implant_ustu_path', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('queue', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelForAddDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('tr_name', models.CharField(default='', max_length=160)),
                ('color', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(max_length=240, null=True)),
                ('last_name', models.CharField(max_length=240, null=True)),
                ('full_name', models.CharField(blank=True, max_length=480, null=True)),
                ('email', models.EmailField(blank=True, max_length=160, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=240, null=True)),
                ('patient_id', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('file_no', models.CharField(blank=True, max_length=240, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('favorited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPageIllnessDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('before_tooth_numbers_text_tr', models.CharField(blank=True, max_length=200, null=True)),
                ('before_tooth_numbers_text_en', models.CharField(blank=True, max_length=200, null=True)),
                ('after_tooth_numbers_text_tr', models.CharField(blank=True, max_length=200, null=True)),
                ('after_tooth_numbers_text_en', models.CharField(blank=True, max_length=200, null=True)),
                ('radiography_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_prediction', models.IntegerField()),
                ('number_correction', models.IntegerField(blank=True, null=True)),
                ('number_edited', models.IntegerField(blank=True, null=True)),
                ('path', models.ImageField(upload_to='single_tooth')),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=1000, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('new_approve_status', models.CharField(choices=[('0', 'blank'), ('1', 'approved'), ('2', 'rejected')], default='0', max_length=100)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('wronged', models.BooleanField(default=False)),
                ('wronged_date', models.DateTimeField(blank=True, null=True)),
                ('approve_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ToothTypeIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('icon_path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_treatment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('en_treatment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('log_page', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecommendationForTooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.imagereport')),
                ('recommendation', models.ManyToManyField(blank=True, null=True, to='Application.TreatmentMethod')),
                ('tooth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.reporttooth')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('updated_planning', ckeditor.fields.RichTextField(blank=True)),
                ('ai_planning', ckeditor.fields.RichTextField(blank=True)),
                ('image_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.imagereport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportToothPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(blank=True, max_length=240, null=True)),
                ('correction', models.CharField(blank=True, max_length=240, null=True)),
                ('treatment_recommendation', models.CharField(blank=True, max_length=240, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('new_approve', models.CharField(choices=[('0', 'blank'), ('1', 'approved'), ('2', 'rejected')], default='0', max_length=100)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_illness', models.BooleanField(default=False)),
                ('approve_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
                ('report_tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.reporttooth')),
            ],
        ),
        migrations.AddField(
            model_name='reporttooth',
            name='icon_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Application.toothtypeicon'),
        ),
        migrations.AddField(
            model_name='reporttooth',
            name='image_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.imagereport'),
        ),
        migrations.CreateModel(
            name='ReportMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateTimeField(blank=True, null=True)),
                ('report_slug', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.patient')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.patient'),
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.imagetype'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
        migrations.CreateModel(
            name='IllnessTreatmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiography_type', models.TextField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('label', models.ManyToManyField(blank=True, null=True, to='Application.IllnessLabel')),
                ('treatment_method', models.ManyToManyField(blank=True, null=True, to='Application.TreatmentMethod')),
            ],
        ),
        migrations.CreateModel(
            name='FormWithCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('form_slug', models.CharField(blank=True, max_length=32, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.company')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.formquestion')),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_slug', models.CharField(max_length=32)),
                ('group_slug', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('specify', models.CharField(blank=True, max_length=255, null=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.formwithcompany')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorChoicesForReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, choices=[('SGK', 'SGK'), ('PATIENT', 'PATIENT'), ('DENTIST', 'DENTIST')], max_length=100, null=True)),
                ('filter_report_based', models.CharField(blank=True, choices=[('PATIENT', 'PATIENT'), ('TOOTH', 'TOOTH')], max_length=100, null=True)),
                ('choices', models.ManyToManyField(blank=True, max_length=100, null=True, to='Application.CreateReportForPatientOptions')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DicomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('image_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.imagereport')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Application.dicomanalysistype')),
            ],
        ),
        migrations.CreateModel(
            name='CreateReportForPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('SGK', 'SGK'), ('PATIENT', 'PATIENT'), ('DENTIST', 'DENTIST')], max_length=100)),
                ('filter_report_based', models.CharField(choices=[('PATIENT', 'PATIENT'), ('TOOTH', 'TOOTH')], max_length=100)),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('drawed_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('image_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.imagereport')),
                ('options', models.ManyToManyField(blank=True, max_length=100, null=True, to='Application.CreateReportForPatientOptions')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedPortalTermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisDetailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('image_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.imagereport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
