# Generated by Django 3.2.16 on 2023-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='illnesslabel',
            name='illness_slug',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
