# Generated by Django 4.2.3 on 2023-09-04 10:18

import Application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_auto_20230718_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagereport',
            name='implant_path',
        ),
        migrations.RemoveField(
            model_name='imagereport',
            name='implant_ustu_path',
        ),
        migrations.RemoveField(
            model_name='imagereport',
            name='is_have_lesion',
        ),
        migrations.AddField(
            model_name='imagereport',
            name='ai_response_image_type',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='imagereport',
            name='cbct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to=Application.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.image'),
        ),
        migrations.CreateModel(
            name='SuggestImplantToMissingTooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(blank=True, max_length=3, null=True)),
                ('image_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.imagereport')),
                ('recommendation', models.ManyToManyField(blank=True, null=True, to='Application.treatmentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='DrawedTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=200, null=True)),
                ('transform', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, choices=[('Crown', 'Crown'), ('Implant', 'Implant')], max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('image_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.imagereport')),
            ],
        ),
    ]
