# Generated by Django 4.2.3 on 2023-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_remove_imagereport_implant_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawedImplantOrCrown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('item_type', models.CharField(choices=[('implant', 'Implant'), ('crown', 'Crown')], max_length=10, null=True)),
                ('icon_id', models.IntegerField(null=True)),
                ('coordinate', models.CharField(max_length=50, null=True)),
                ('dimension', models.IntegerField(null=True)),
                ('rotate', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginpage_logo_design', models.FileField(blank=True, null=True, upload_to='static/img')),
                ('loginpage_banner', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('base_html_css', models.FileField(blank=True, null=True, upload_to='static/css')),
                ('base_html_left_top_logo', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('base_html_left_bottom_title', models.CharField(blank=True, max_length=50, null=True)),
                ('language_visibility', models.BooleanField(default=False)),
                ('page_title', models.CharField(blank=True, max_length=50, null=True)),
                ('report_page_title_banner', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('clarification_text', models.FileField(blank=True, null=True, upload_to='static/pdf')),
                ('cookie_policy', models.FileField(blank=True, null=True, upload_to='static/pdf')),
                ('privacy_policy', models.FileField(blank=True, null=True, upload_to='static/pdf')),
                ('login_page_content', models.TextField(blank=True, null=True)),
                ('website_link', models.CharField(blank=True, max_length=50, null=True)),
                ('website_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='createreportforpatient',
            name='options',
            field=models.ManyToManyField(blank=True, max_length=100, to='Application.createreportforpatientoptions'),
        ),
        migrations.AlterField(
            model_name='doctorchoicesforreport',
            name='choices',
            field=models.ManyToManyField(blank=True, max_length=100, to='Application.createreportforpatientoptions'),
        ),
        migrations.AlterField(
            model_name='illnesstreatmentmethod',
            name='label',
            field=models.ManyToManyField(blank=True, to='Application.illnesslabel'),
        ),
        migrations.AlterField(
            model_name='illnesstreatmentmethod',
            name='treatment_method',
            field=models.ManyToManyField(blank=True, to='Application.treatmentmethod'),
        ),
        migrations.AlterField(
            model_name='suggestimplanttomissingtooth',
            name='recommendation',
            field=models.ManyToManyField(blank=True, to='Application.treatmentmethod'),
        ),
        migrations.AlterField(
            model_name='treatmentrecommendationfortooth',
            name='recommendation',
            field=models.ManyToManyField(blank=True, to='Application.treatmentmethod'),
        ),
    ]
