# Generated by Django 4.2.3 on 2023-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_formquestion_formwithcompany_formanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='manual_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
