# Generated by Django 4.2.3 on 2023-10-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_formquestion_manual_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormRadiographs',
        ),
    ]
