# Generated by Django 4.2.3 on 2023-10-04 10:59

import Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_delete_formradiographs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormRadiographs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_answer_group_slug', models.CharField(max_length=100)),
                ('path', models.ImageField(upload_to=Application.models.get_file_path)),
            ],
        ),
    ]
