# Generated by Django 4.2.3 on 2023-10-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_formradiographs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': '002. Image'},
        ),
        migrations.AlterModelOptions(
            name='imagereport',
            options={'verbose_name_plural': '004. ImageReport'},
        ),
        migrations.AlterModelOptions(
            name='imagetype',
            options={'verbose_name_plural': '003. ImageType'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': '001. Patient'},
        ),
        migrations.AddField(
            model_name='specificparameter',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='specificparameter',
            name='terms_conditions_policy',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf'),
        ),
    ]
