# Generated by Django 4.2.3 on 2023-11-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_alter_image_options_alter_imagereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawedimplantorcrown',
            name='image_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.imagereport'),
        ),
        migrations.AddField(
            model_name='drawedimplantorcrown',
            name='original_shape',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drawedimplantorcrown',
            name='dimension',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
