# Generated by Django 4.2.3 on 2024-01-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_drawedimplantorcrown_image_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentmethod',
            name='fr_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
