# Generated by Django 4.2.3 on 2024-01-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_treatmentmethod_fr_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentmethod',
            old_name='fr_method',
            new_name='fr_treatment_method',
        ),
    ]
