# Generated by Django 4.2.3 on 2024-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_rename_fr_method_treatmentmethod_fr_treatment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpageillnessdescriptions',
            name='after_tooth_numbers_text_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportpageillnessdescriptions',
            name='before_tooth_numbers_text_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
