# Generated by Django 4.2.3 on 2024-02-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0018_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='createreportforpatient',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='media/qrcodes'),
        ),
    ]
