# Generated by Django 4.2.3 on 2024-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_createreportforpatient_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('traceback_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
