# Generated by Django 4.2.3 on 2024-03-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0020_loginerrorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('folder_path', models.CharField(blank=True, max_length=45, null=True)),
                ('nifti_path', models.CharField(blank=True, max_length=45, null=True)),
                ('result_nifti_path', models.CharField(blank=True, max_length=51, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.patient')),
            ],
        ),
    ]
