# Generated by Django 4.2.3 on 2024-03-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0021_dicomfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagereport',
            name='dicom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.dicomfile'),
        ),
    ]
