# Generated by Django 4.2.3 on 2024-03-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0023_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpageillnessdescriptions',
            name='after_tooth_numbers_text_nl',
        ),
        migrations.RemoveField(
            model_name='reportpageillnessdescriptions',
            name='after_tooth_numbers_text_pt',
        ),
        migrations.RemoveField(
            model_name='reportpageillnessdescriptions',
            name='after_tooth_numbers_text_ru',
        ),
        migrations.RemoveField(
            model_name='reportpageillnessdescriptions',
            name='after_tooth_numbers_text_uz',
        ),
        migrations.RemoveField(
            model_name='reportpageillnessdescriptions',
            name='before_tooth_numbers_text_nl',
        ),
        migrations.RemoveField(
            model_name='reportpageillnessdescriptions',
            name='before_tooth_numbers_text_pt',
        ),
        migrations.RemoveField(
            model_name='reportpageillnessdescriptions',
            name='before_tooth_numbers_text_ru',
        ),
        migrations.RemoveField(
            model_name='reportpageillnessdescriptions',
            name='before_tooth_numbers_text_uz',
        ),
        migrations.RemoveField(
            model_name='treatmentmethod',
            name='nl_treatment_method',
        ),
        migrations.RemoveField(
            model_name='treatmentmethod',
            name='pt_treatment_method',
        ),
        migrations.RemoveField(
            model_name='treatmentmethod',
            name='ru_treatment_method',
        ),
        migrations.RemoveField(
            model_name='treatmentmethod',
            name='uz_treatment_method',
        ),
    ]
