"""
Django settings for CCClinic project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fs9bn_iqg!q-n9-u%xm0ls*46b@l9jb9t&qat0zbow@z71a8s1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# ALLOWED_HOSTS = ["www.google.com",'aiv2.craniocatch.com','app.craniocatch.com', 'www.app.craniocatch.com', '34.90.2.206','93.89.73.104', 'www.craniocatch.com', 'craniocatch.com', 'cranio-test-server-gpu.europe-west4-a.c.utility-canto-365904.internal','229.84.90.34.bc.googleusercontent.com']
ALLOWED_HOSTS = ["*"]
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_HTTPONLY = True


# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# # SECURE_SSL_REDIRECT = True
# # Güvenli çerezler için HTTPS gereklidir
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# # Kötü niyetli iframe'lere karşı koruma sağlar
# X_FRAME_OPTIONS = 'DENY'
# # Güvenli içerikleri zorla (Strict-Transport-Security - HSTS)
# SECURE_HSTS_SECONDS = 31536000  # Örnek değer: 1 yıl
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'adminlte3',
    'adminlte3_theme',
    'Application',
    'Wizard',
    'User',
    'rosetta',
    'corsheaders',
    'ckeditor',
    'Application3d',
    'rest_framework',
    'agent',
    'AdminPanel',
    # 'oauth2_provider',
    'rest_framework.authtoken',    
    # 'debug_toolbar',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# CORS_ALLOW_ALL_ORIGINS = False  # Herhangi bir kök etki alanına izin verme
CORS_ALLOWED_ORIGINS = [
    "http://93.89.72.58:443",
    "http://93.89.72.58",  # İzin vermek istediğiniz kök etki alanı
    "https://ai.thakaamed.com",
    "https://dcm.craniocatch.com",
    "http://35.208.148.229",
    "http://95.177.165.72:*",
    "http://95.177.165.72",
    "http://95.177.165.72:8007", 
    "https://www.thakaamed.com", 
    "https://thakaamed.com"
]

CSRF_TRUSTED_ORIGINS = ["https://ai.thakaamed.com", "http://35.208.148.229", "https://dcm.craniocatch.com","http://95.177.165.72:*",
    "http://95.177.165.72","http://95.177.165.72:8007", "https://www.thakaamed.com", "https://thakaamed.com"]

ROOT_URLCONF = 'Server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'Server.wsgi.application'
ASGI_APPLICATION = 'Server.asgi.application'  # new

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# 20 MB (20 * 1024 * 1024 bytes)
DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024

# 20 MB (20 * 1024 * 1024 bytes)
FILE_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'thakaa',
        'USER': 'thakaauser',
        'PASSWORD': '9HRs6e2cb2Z2h2SKyp',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
clinic_project_id = 2

if clinic_project_id == 1:
    LANGUAGES = (
        ('en', ('English')),
        ('tr', ('Turkish')),
        ('ar', ('Arabic')),
        ('pt', ('Portuguese')),
        ('uz', ('Uzbec')),
        ('ru', ('Russian')),
        ("nl", ("Dutch")),
    )
else:
    LANGUAGES = (
        ('en', ('English')),
        ('ar', ('Arabic')),
    )

ROSETTA_MESSAGES_SOURCE_LANGUAGE_CODE = "en"
ROSETTA_MESSAGES_SOURCE_LANGUAGE_NAME = "English"

LANGUAGES = (
    ('en', ('English')),
    ('fr', ('French')),
    # ('tr', ('Turkish')),
)

LOCALE_PATHS = (os.path.join(BASE_DIR, 'locale'),)

LOGIN_URL = '/login/'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

server_type = "LIVE SERVER"
image_path_without_slash_after_media = "/home/ubuntu/Clinic/media"
ccclinic_path = "/home/ubuntu/Clinic"
ccclinic_path_with_slash = "/home/ubuntu/Clinic/"
ccreport_url = "https://ai.thakaamed.com/en/report/"
cc_url = "https://ai.thakaamed.com"
ccreport_url_tr = "https://ai.thakaamed.com/tr/report/"
ccreport_url_fr = "https://ai.thakaamed.com/fr/report/"
dicom_server_url = 'http://35.208.148.229:8001'
dicom_base_path = "/home/akilliceviribilisim/CCAI3Dv1"
patient_form_link = "http://ai.thakaamed.com/web-form/"
add_patient_form_site_link = "http://ai.thakaamed.com"

DATA_UPLOAD_MAX_MEMORY_SIZE = 3048576000  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 3048576000  # 2.5 MB
# FILE_UPLOAD_TEMP_DIR = 3048576000  # 25 MB
# dcmServerUrl = "http://172.208.89.171:8000"
dcmServerUrl = "https://dcm.craniocatch.com"
company_api_key = "5C7A3A886A1D4103BFBCD4A662BACA53"

AIServerUrlDict = {"8010": "https://aiv2.craniocatch.com", "8007": "https://aiv4.craniocatch.com", "8006": "https://aiv4.craniocatch.com", "8080": "https://aiv4.craniocatch.com", "8005": "http://20.13.137.64:8008"}
AIServerUrl = AIServerUrlDict['8080']

import sys
import socket
full_port = socket.gethostbyname(socket.gethostname())+"----"+sys.argv[-1]
running_port = full_port[len(full_port)-4:]
print("running_port", running_port)

if running_port in AIServerUrlDict.keys():
    AIServerUrl = AIServerUrlDict[running_port]
print("AIServerUrl: ", AIServerUrl)
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "main_formatter": {
            "format": "{asctime} - {levelname} - {module} - {message} ",
            "style": "{",
        },
    },
    "handlers": {
        'console': {
            'class': "logging.StreamHandler",
            'formatter':'main_formatter',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'info.log',
            'formatter': 'main_formatter',
        },
    },
    "loggers": {
        'main': {
            'handlers': ['file','console'],
            'propagate': True,
            'level': 'INFO' #info and above the info
        }
    }
}

lateral_cephalometric_dict = {
    "Soft Nose": [
        "Glabella (G’)",
        "Soft Tissue Nasion (N’)",
        "Nasal Dorsum",
        "Pronasale (Pn)",
        "Columella (Cm)",
        "Subnasale (Sn)"
    ],
    "Upper Lip": [
        "Soft Tissue A point (A’)",
        "Labrale superior (Ls)",
        "Stomion superius (Ss)"
    ],
    "Lower Lip": [
        "Stomion inferius (Si)",
        "Labiale inferior (Li)",
        "Soft Tissue B point (B’)"
    ],
    "Soft Chin": [
        "Soft tissue Pogonion (Pg’)",
        "Gnathion Soft Tissue (Gn’)",
        "Soft tissue Menton (Me’)"
    ],
    "Jaw": [
        "Pogonion (Pg)",
        "Gnathion (Gn)",
        "Menton (Me)",
        "Gonion (Go)",
        "Ramus (Ra)",
        "Articulare (Ar)"
    ],

}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.craniocatch.com'  # E-posta sunucusunun adresi
EMAIL_PORT = 587  # E-posta sunucusunun portu
EMAIL_USE_TLS = True  # TLS kullanılıp kullanılmayacağı
EMAIL_USE_SSL = False  # SSL kullanılıp kullanılmayacağı
EMAIL_HOST_USER = 'teknik@craniocatch.com'  # E-posta hesabınızın kullanıcı adı
EMAIL_HOST_PASSWORD = '.=4-CzHB6yvtM20='  # E-posta hesabınızın şifresi

from Application.cache_processes import cache_updater_function, cache_all_updater_function

cache_updater_function()
cache_all_updater_function()