# Generated by Django 4.2.3 on 2023-09-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application3d', '0002_dicomanalysistype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomanalysistype',
            name='tr_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dicomanalysistype',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dicomreport',
            name='slug',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
