# Generated by Django 4.2.3 on 2024-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application3d', '0003_dicomanalysistype_tr_name_dicomanalysistype_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomanalysistype',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
