# Generated by Django 4.2.3 on 2024-03-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application3d', '0004_dicomanalysistype_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomreport',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
