# Generated by Django 3.2.16 on 2023-07-13 11:16

import User.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos')),
                ('email', models.EmailField(blank=True, max_length=160, null=True)),
                ('website', models.CharField(blank=True, max_length=160, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreateUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=User.models.get_file_path_for_signature)),
                ('clinic_logo', models.ImageField(blank=True, null=True, upload_to=User.models.get_file_path_for_clinic_logo)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=User.models.get_file_path)),
                ('user_type', models.CharField(choices=[('CranioCatch Group', 'CranioCatch Group'), ('Customer', 'Customer')], default='Customer', max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=120, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('creator_username', models.CharField(blank=True, max_length=120, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsagePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=20)),
                ('pack_name_en', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_limit', models.IntegerField()),
                ('image_limit', models.IntegerField()),
                ('analysis_limit', models.IntegerField()),
                ('key', models.CharField(blank=True, max_length=160, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('global_price', models.FloatField(blank=True, default=0, null=True)),
                ('is_yearly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('tr', 'TR'), ('en', 'EN')], default='tr', max_length=2, verbose_name='Dil')),
                ('color', models.CharField(choices=[('dark', 'DARK'), ('light', 'LIGHT')], default='dark', max_length=5, verbose_name='Renk')),
                ('page_length', models.CharField(choices=[('5', '5'), ('10', '10'), ('25', '25'), ('50', '50'), ('Hepsi', 'Hepsi')], default='10', max_length=5, verbose_name='Hasta Listeleme Adedi')),
                ('card_view_type', models.CharField(choices=[('0', 'LIST'), ('1', 'CARD')], default='0', max_length=5, verbose_name='Hasta Görüntüleme Türü')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserForgotPasswordKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=6, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile', verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='UsagePackageWithProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trxCode', models.CharField(blank=True, max_length=255, null=True)),
                ('trxCodeCranio', models.CharField(blank=True, max_length=255, null=True)),
                ('result_message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_valid', models.BooleanField(blank=True, default=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
                ('usage_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usagepackage')),
            ],
        ),
    ]
