# Generated by Django 4.2.3 on 2023-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20230828_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='language',
            field=models.CharField(choices=[('tr', 'TR'), ('en', 'EN')], default='en', max_length=2, verbose_name='Dil'),
        ),
    ]
