# Generated by Django 4.2.3 on 2023-10-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_usertheme_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyedExtraPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('token', models.IntegerField()),
                ('price', models.CharField(blank=True, max_length=32, null=True)),
                ('price_per_token', models.CharField(blank=True, max_length=32, null=True)),
                ('currency', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('audience', models.IntegerField()),
                ('monthly_price', models.CharField(blank=True, max_length=32, null=True)),
                ('token', models.IntegerField()),
                ('price_per_token', models.CharField(blank=True, max_length=32, null=True)),
                ('currency', models.CharField(blank=True, max_length=32, null=True)),
                ('is_yearly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='clinic_logo',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_owner_of_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/clinic_logo'),
        ),
        migrations.AlterField(
            model_name='usertheme',
            name='language',
            field=models.CharField(choices=[('tr', 'TR'), ('en', 'EN')], default='tr', max_length=2, verbose_name='Dil'),
        ),
        migrations.CreateModel(
            name='UserTokenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyed_package_or_extra_slug', models.CharField(blank=True, max_length=32, null=True)),
                ('used_token', models.IntegerField()),
                ('image_type', models.CharField(choices=[('Panaromic', 'Panaromic'), ('Bitewing', 'Bitewing'), ('CBCT', 'CBCT'), ('Periapical', 'Periapical'), ('Lateral Cephalometric', 'Lateral Cephalometric')], max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PackageRemainingUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('usage', models.IntegerField(default=0)),
                ('total_usage', models.IntegerField(default=0)),
                ('usage_limit', models.IntegerField(default=0)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('next_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('buyed_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.buyedpackage')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPackageRemainingUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('usage', models.IntegerField(default=0)),
                ('total_usage', models.IntegerField(default=0)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('next_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('buyed_extra_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.buyedextrapackage')),
            ],
        ),
        migrations.AddField(
            model_name='buyedpackage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.company'),
        ),
        migrations.AddField(
            model_name='buyedpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.package'),
        ),
        migrations.AddField(
            model_name='buyedpackage',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='User.profile'),
        ),
        migrations.AddField(
            model_name='buyedextrapackage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.company'),
        ),
        migrations.AddField(
            model_name='buyedextrapackage',
            name='extra_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.extrapackage'),
        ),
    ]
