# Generated by Django 4.2.3 on 2023-10-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_buyedextrapackage_buyedpackage_extrapackage_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('equal', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThakaaBuyedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.company')),
            ],
            options={
                'verbose_name_plural': '54. ThakaaBuyedToken',
            },
        ),
        migrations.CreateModel(
            name='ThakaaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('audience', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '51. ThakaaPackage',
            },
        ),
        migrations.CreateModel(
            name='ThakaaRemainingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('usage', models.IntegerField(default=0)),
                ('total_usage', models.IntegerField(default=0)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('next_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('cranio_buyed_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.thakaabuyedtoken')),
            ],
            options={
                'verbose_name_plural': '55. ThakaaRemainingToken',
            },
        ),
        migrations.CreateModel(
            name='ThakaaTokenBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('token', models.IntegerField()),
                ('token_per_price', models.FloatField()),
                ('total_price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '52. ThakaaTokenBar',
            },
        ),
        migrations.CreateModel(
            name='ThakaaTokenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_token', models.IntegerField()),
                ('image_type', models.CharField(choices=[('Panaromic', 'Panaromic'), ('Bitewing', 'Bitewing'), ('CBCT', 'CBCT'), ('Periapical', 'Periapical'), ('Lateral Cephalometric', 'Lateral Cephalometric')], max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('cranio_remaining_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.thakaaremainingtoken')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.profile')),
            ],
            options={
                'verbose_name_plural': '56. ThakaaTokenActivity',
            },
        ),
        migrations.AddField(
            model_name='thakaabuyedtoken',
            name='tokenbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.thakaatokenbar'),
        ),
        migrations.CreateModel(
            name='ThakaaBuyedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.company')),
                ('cranio_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.thakaapackage')),
                ('profiles', models.ManyToManyField(blank=True, to='User.profile')),
            ],
            options={
                'verbose_name_plural': '53. ThakaaBuyedPackage',
            },
        ),
    ]
