# Generated by Django 4.2.3 on 2023-10-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_currency_thakaabuyedtoken_thakaapackage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thakaabuyedpackage',
            old_name='cranio_package',
            new_name='thakaa_package',
        ),
        migrations.RenameField(
            model_name='thakaaremainingtoken',
            old_name='cranio_buyed_token',
            new_name='thakaa_buyed_token',
        ),
        migrations.RenameField(
            model_name='thakaatokenactivity',
            old_name='cranio_remaining_token',
            new_name='thakaa_remaining_token',
        ),
    ]
