# Generated by Django 4.2.3 on 2023-11-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_cranio_package_thakaabuyedpackage_thakaa_package_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyedextrapackage',
            options={'verbose_name_plural': '05. BuyedExtraPackage'},
        ),
        migrations.AlterModelOptions(
            name='buyedpackage',
            options={'verbose_name_plural': '02. BuyedPackage'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': '001. Company'},
        ),
        migrations.AlterModelOptions(
            name='extrapackage',
            options={'verbose_name_plural': '04. ExtraPackage'},
        ),
        migrations.AlterModelOptions(
            name='extrapackageremainingusage',
            options={'verbose_name_plural': '06. ExtraPackageRemainingUsage'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name_plural': '01. Package'},
        ),
        migrations.AlterModelOptions(
            name='packageremainingusage',
            options={'verbose_name_plural': '03. PackageRemainingUsage'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '000. Profile'},
        ),
        migrations.AlterModelOptions(
            name='usertokenactivity',
            options={'verbose_name_plural': '11. UserTokenActivity'},
        ),
        migrations.AddField(
            model_name='usertheme',
            name='arabic',
            field=models.BooleanField(default=False),
        ),
    ]
