# Generated by Django 4.2.3 on 2024-01-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_buyedextrapackage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='language',
            field=models.CharField(choices=[('tr', 'TR'), ('en', 'EN'), ('fr', 'FR')], default='tr', max_length=2, verbose_name='Dil'),
        ),
    ]
