# Generated by Django 4.2.3 on 2024-02-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_usertheme_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='added_by_distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_distributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertheme',
            name='language',
            field=models.CharField(choices=[('tr', 'TR'), ('en', 'EN'), ('fr', 'FR')], default='en', max_length=2, verbose_name='Dil'),
        ),
    ]
