# Generated by Django 4.2.3 on 2024-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_purchaserecord_packagepricing_extrapackagepricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=160, null=True)),
                ('phone', models.CharField(blank=True, max_length=160, null=True)),
                ('company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('total_price', models.CharField(blank=True, max_length=100, null=True)),
                ('price_per_token', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('OtherTrxCode', models.CharField(blank=True, max_length=100, null=True)),
                ('code_for_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('request_payment_details', models.TextField(blank=True, null=True)),
                ('redirect_payment_details', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('trxCode', models.CharField(blank=True, max_length=100, null=True)),
                ('resultMessage', models.TextField(blank=True, null=True)),
                ('payment_method', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
