# Generated by Django 4.2.3 on 2024-03-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_tokenpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='language',
            field=models.CharField(choices=[('en', 'EN'), ('fr', 'FR')], default='en', max_length=2, verbose_name='Dil'),
        ),
    ]
