# Generated by Django 4.2.3 on 2024-03-19 07:58

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_usertheme_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pdf_cover',
            field=models.ImageField(blank=True, null=True, upload_to=User.models.get_file_path_for_pdf_cover),
        ),
        migrations.AddField(
            model_name='company',
            name='pdf_finish_cover',
            field=models.ImageField(blank=True, null=True, upload_to=User.models.get_file_path_for_pdf_cover),
        ),
    ]
