from Application.views import *
from Application.api.views import *
from Application.api.analyze import *
from django.urls import path

from Application.api.thirdparty import RadiographyAnalyzeApi


urlpatterns = [
    path("add-patient-api", add_patient_api, name="addpatientApi"),
    path("delete-patient-api", delete_patient_api, name="deletepatientApi"),
    path("change_favorite_status", change_favorite_status, name="changefavoritestatusApi"),
    path("update_page_length", update_page_length, name="updatepagelengthApi"),
    path("change_card_view", change_card_view, name="changecardviewApi"),
    path("change_theme_view", change_theme_view, name="changethemeviewApi"),
    path("change_tooth_approved_status", change_tooth_approved_status, name="changetoothapprovedstatusviewApi"),
    path("get_notifications", get_notifications, name="getnotificationsApi"),
    path("get_user_info", get_user_info, name="get_user_info"),
    path("process_status_for_notification", process_status_for_notification, name="processStatusForNotificationApi"),
    path("update-profile", update_profile, name="update_profile"),
    path("change_language", change_language, name="changelanguageApi"),
    path("save_profile_photo", save_profile_photo, name="save_profile_photo"),
    path("save_signature", save_signature, name="save_signature"),
    path("save_clinic_logo", save_clinic_logo, name="save_clinic_logo"),
    path("save_tooth_note", save_tooth_note, name="saveToothNoteApi"),
    path("update_password", update_password, name="update_password"),
    path("update_reportTooth", api_update_report_tooth, name="updateReportTooth"),
    path('illness-draw/', illness_draw, name="illnessDraw"),
    path('start_analyze', start_analyze, name='startAnalyze'),
    path('is-analyse-finished', is_analyze_finished, name='is_analyze_finished'),
    path('add-diagnosis', add_diagnosis, name='add_diagnosis'),
    path('add-treatment', add_treatment, name='add_treatment'),
    path('add-treatment-planning', add_treatment_planning, name='add_treatment_planning'),
    path('get-treatment-planning-content', get_content_of_treatment_planning, name='get_content_of_treatment_planning'),
    path('upload/', upload_radyografi, name='upload_radyografi'),
    path('delete-treatment-planning/', delete_treatment_plan, name='delete_treatment_plan'),
    path('change_approve_status', change_approve_status, name='change_approve_status'),
    path('delete-illness-from-tooth', delete_illness_from_tooth, name='delete_illness_from_tooth'),
    path('delete-treatment-from-tooth', delete_treatment_from_tooth, name='delete_treatment_from_tooth'),
    path('create-report-for-patient', createReportForPatient, name='createReportForPatient'),
    path('send-report-mail', sendReportMail, name='sendReportMail'),
    path('save-doctor-note', save_doctor_note, name='save_doctor_note'),
    path('save_doctor_choices', save_doctor_choices, name='save_doctor_choices'),
    # path('add_slug_to_treatment_methods', add_slug_to_treatment_methods, name='add_slug_to_treatment_methods'),
    path('get_current_lang', get_current_lang, name='get_current_lang'),
    path('save_demo_user_api', save_demo_user_api, name='save_demo_user_api'),
    path('Buy/Product/', buy_product, name='buy_product'),
    path('Buy/buy_product_result/', buy_product_result, name='buy_product_result'),
    path('all-diseases', all_diseases, name='all_diseases'),
    path('company-form-create-update', formCreateUpdateForCompany, name='formCreateUpdateForCompany'),
    path('save-patient-form', save_patient_form, name='save_patient_form'),
    # path('upload-radiography-from-form', upload_radiography_from_form, name='upload_radiography_from_form'),
    path('save-drawed-diagnosis', save_drawed_diagnosis, name='save_drawed_diagnosis'),
    path('patients-for-datatable', PatientsForDatatable.as_view(), name='PatientsForDatatable'),
    path('download-drawed-radiography/', download_drawed_radiography_button, name="downloadDrawedRadiographyButton"),
    path('delete-drawed-illness', delete_drawed_illness, name="deleteDrawedIllness"),
    path('delete-user', delete_user, name="delete_user"),
    path('get-manuel-calibration', get_manuel_calibration, name="getManuelCalibration"),
    path('archive-image', archive_image, name="archiveImage"),
    path('drawTreatmentPlan', draw_treatment_plan, name="drawTreatmentPlan"),
    path('save-implant-or-crown', save_implant_or_crown, name="saveImplantOrCrown"),
    path('delete-implant-or-crown', delete_implant_or_crown, name="deleteImplantOrCrown"),
    path('token-informations', get_token_informations, name="getTokenInfo"),
    path('update-lateral-points', update_lateral_points, name="updateLateralPoints"),
    path('active-arabic', active_arabic, name="activeArabic"),

    path('v<api_version>/analyze/radiography/', RadiographyAnalyzeApi.as_view()),
    path('check_user_and_token', check_user_and_token),
    path('create_user_from_website', create_user_from_website),
    path('convert_tiff_to_png_js', convert_tiff_to_png_js, name="convert_tiff_to_png_js"),
    path('logout-function', logout_save, name="logout_save"),
    path('cache-signal-from-ai/', AICacheUpdateSignal, name="AICacheUpdateSignal"),
    path('callback', callback, name='callback'),
    path('feedback', feedback, name='feedback'),
    path('add-user-api', AddPanelApi.addDoctorOwnCompany, name='addDoctorOwnCompanyApi'),
    path('add-user-distributor-api', AddPanelApi.addDistributor, name='addDistributorApi'),
    path('add-user-to-company-api', AddPanelApi.addDoctorDifferentCompany, name='addDoctorDifferentCompanyApi'),
    path('add-user-and-company-api', AddPanelApi.addCompanyDoctor, name='addCompanyDoctorApi'),
    path('add-demo-user-api', AddPanelApi.addDemoUser, name='addDemoUserApi'),
    path('distributor-adds-user-api', AddPanelApi.DistributorAddsUser, name='DistributorAddsUserApi'),
    path('distributor-adds-user-to-company-api', AddPanelApi.DistributorAddsUserToCompany, name='DistributorAddsUserToCompanyApi'),
    path('patient_past?analysis', patient_past_analysis, name='patientPastAnalysis'),
    path('start-failed-analysis', start_failed_analysis, name='startFailedAnalysis'),
]